language: scala

sudo: false

scala:
  - "2.12.11"
  - "2.13.1"

jdk:
  - openjdk8

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";compile"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot